In [76]:
import pandas as pd
import re
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
import time

In [77]:
driver= webdriver.Chrome("C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")
driver.maximize_window()
driver.implicitly_wait(20)
driver.get("http://www.linkedin.com")

<ipython-input-77-db71e2e376f2>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver= webdriver.Chrome("C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [78]:
wait=WebDriverWait(driver, 5)

In [79]:
wait.until(EC.presence_of_element_located((By.XPATH, "//a[@class='nav__button-secondary']")))
driver.find_element(By.XPATH,'//a[@class="nav__button-secondary"]').click()

In [80]:
wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="username"]')))
driver.find_element(By.XPATH,'//*[@id="username"]').send_keys("charanrajshetty1993@gmail.com")

wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="password"]')))
driver.find_element(By.XPATH,'//*[@id="password"]').send_keys("Charan@1993")

wait.until(EC.presence_of_element_located((By.XPATH, '//button[text()="Sign in"]')))
driver.find_element(By.XPATH,'//button[text()="Sign in"]').click()

In [81]:
jobs=pd.read_csv('Job_Links_1 - Copy.csv')

In [82]:
jobs.shape

(30108, 11)

In [97]:
jobs.loc[27571,:]

Unnamed: 0                                                       27100
City                                                     New York City
Rank                                                               201
Company                                                          Slice
Industry                                                          Food
Funding                                                          $125M
Employees                                                          627
Employee_Growth                                                    16%
Current_Jobs                                                        14
Job_Links                 http://www.linkedin.com/company/mypizza/jobs
job_url              https://www.linkedin.com/jobs/view/2409474831/...
Job_title                                                          NaN
Location                                                           NaN
Job_Level                                                          NaN
JobRecruit_Status                                                  NaN
Name: 27571, dtype: object

In [98]:
for item in range(27571,30108):
    driver.get(jobs.loc[item,'job_url'])
    try:
        wait.until(EC.presence_of_element_located((By.XPATH, "//h1[contains(@class,'t-bold')]")))
        jobs.loc[item,'Job_title']=driver.find_element(By.XPATH,"//h1[contains(@class,'t-bold')]").text
    
        wait.until(EC.presence_of_element_located((By.XPATH, "//span[contains(@class,'bullet')]")))
        jobs.loc[item,'Location']=driver.find_element(By.XPATH,"//span[contains(@class,'bullet')]").text
    
        wait.until(EC.presence_of_element_located((By.XPATH, "//div[contains(@class,'job-insight')][1]//span[1]")))
        jobs.loc[item,'Job_Level']=driver.find_element(By.XPATH,"//div[contains(@class,'job-insight')][1]//span[1]").text
    
        try:
            wait.until(EC.presence_of_element_located(   (By.XPATH, "//div[contains(@class,'job-insight')]//span[text()='Actively recruiting']")))
            jobs.loc[item,'JobRecruit_Status']=driver.find_element(By.XPATH,"//div[contains(@class,'job-insight')]//span[text()='Actively recruiting']").text
        except:
            jobs.loc[item,'JobRecruit_Status']='No Active recruit'
    except:
        continue

In [99]:
jobs

,Unnamed: 0,City,Rank,Company,Industry,Funding,Employees,Employee_Growth,Current_Jobs,Job_Links,job_url,Job_title,Location,Job_Level,JobRecruit_Status
0,0,Atlanta,1,SnapNurse,HRTech,NaN,344,648%,1,http://www.linkedin.com/company/snapnurse/jobs,https://www.linkedin.com/jobs/view/2787120903/...,NaN,NaN,NaN,NaN
1,1,Atlanta,1,SnapNurse,HRTech,NaN,344,648%,1,http://www.linkedin.com/company/snapnurse/jobs,https://www.linkedin.com/jobs/view/2791491729/...,NaN,NaN,NaN,NaN
2,2,Atlanta,1,SnapNurse,HRTech,NaN,344,648%,1,http://www.linkedin.com/company/snapnurse/jobs,https://www.linkedin.com/jobs/view/2816885680/...,NaN,NaN,NaN,NaN
3,3,Atlanta,1,SnapNurse,HRTech,NaN,344,648%,1,http://www.linkedin.com/company/snapnurse/jobs,https://www.linkedin.com/jobs/view/2818540382/...,NaN,NaN,NaN,NaN
4,4,Atlanta,1,SnapNurse,HRTech,NaN,344,648%,1,http://www.linkedin.com/company/snapnurse/jobs,https://www.linkedin.com/jobs/view/2797744025/...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30103,29632,Charlotte,76,Hyper Networks,Telecom,NaN,48,30%,1,http://www.linkedin.com/company/hyper-networks...,https://www.linkedin.com/jobs/view/2823938686/...,Quality Assurance Specialist,Raleigh-Durham-Chapel Hill Area,"$44,000/yr - $69,000/yr (LinkedIn est.) · Full...",Actively recruiting
30104,29633,Charlotte,79,CARE | Charlott...,Veterinary,NaN,46,15%,1,http://www.linkedin.com/company/care-charlotte...,https://www.linkedin.com/jobs/view/2733014740/...,Registered Veterinary Technician/ Experienced ...,"North Carolina, United States",$22/hr - $28/hr · Full-time,No Active recruit
30105,29634,Charlotte,81,Sprout,Information Technology & Services,$400K,59,0%,1,http://www.linkedin.com/company/smr-worldwide/...,https://www.linkedin.com/jobs/view/2829842078/...,International Logistics Manager,United States,Full-time · Mid-Senior level,Actively recruiting
30106,29635,Charlotte,81,Sprout,Information Technology & Services,$400K,59,0%,1,http://www.linkedin.com/company/smr-worldwide/...,https://www.linkedin.com/jobs/view/2809585026/...,Account Manager,United States,Full-time · Mid-Senior level,Actively recruiting
30107,29636,Charlotte,81,Sprout,Information Technology & Services,$400K,59,0%,1,http://www.linkedin.com/company/smr-worldwide/...,https://www.linkedin.com/jobs/view/2834840899/...,Pediatric Dental Assistant,"McKinney, TX",Part-time · Entry level,Actively recruiting

In [ ]:
jobs.to_csv('Job_Details_2.csv')